name: ai_diary
description: "A diary enhanced with Gemini."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  animated_icon: ^0.0.9
  cloud_firestore: ^5.2.0
  date_picker_plus: ^4.1.0
  email_validator: ^3.0.0
  firebase_auth: ^5.1.3
  firebase_core: ^3.3.0
  firebase_vertexai: ^0.2.2+4
  flutter:
    sdk: flutter
  flutter_gemini: ^2.0.4
  image_picker: ^1.1.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
