// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCohd8jx-rOTIZC9-5bYfWoNnlKYsf-w24',
    appId: '1:548356502125:web:e758c0510baeba8a41c564',
    messagingSenderId: '548356502125',
    projectId: 'aidiary-d7513',
    authDomain: 'aidiary-d7513.firebaseapp.com',
    storageBucket: 'aidiary-d7513.appspot.com',
    measurementId: 'G-PVV0TMBQ6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6lLqLTucQjI81bJitdfMsfO7-LlXMYQo',
    appId: '1:548356502125:android:bbe0ab31dcbd77af41c564',
    messagingSenderId: '548356502125',
    projectId: 'aidiary-d7513',
    storageBucket: 'aidiary-d7513.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_6XuHpVItdrPex-pXGz7drjBYRT5nDJc',
    appId: '1:548356502125:ios:b672545560f85d5341c564',
    messagingSenderId: '548356502125',
    projectId: 'aidiary-d7513',
    storageBucket: 'aidiary-d7513.appspot.com',
    iosBundleId: 'com.example.aiDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_6XuHpVItdrPex-pXGz7drjBYRT5nDJc',
    appId: '1:548356502125:ios:76ebb71c58b1a56f41c564',
    messagingSenderId: '548356502125',
    projectId: 'aidiary-d7513',
    storageBucket: 'aidiary-d7513.appspot.com',
    iosBundleId: 'com.example.aiDiary.RunnerTests',
  );
}
